server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway

  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:3000"
#            allowedMethods: 
#                - GET
#                - POST
            
      routes:
        - id: inventory-management
          uri: lb://inventory-management
          predicates:
            - Path=/api/products/**
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/auth/**
            
            
            
            